/* Generated By:JavaCC: Do not edit this line. Lexer2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 7;
  /** RegularExpression Id. */
  int EXTENDS = 8;
  /** RegularExpression Id. */
  int STATIC = 9;
  /** RegularExpression Id. */
  int PUBLIC = 10;
  /** RegularExpression Id. */
  int MAIN = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int NEW = 19;
  /** RegularExpression Id. */
  int THIS = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int RETURN = 24;
  /** RegularExpression Id. */
  int SYSTEM = 25;
  /** RegularExpression Id. */
  int OUT = 26;
  /** RegularExpression Id. */
  int PRINTLN = 27;
  /** RegularExpression Id. */
  int ID = 28;
  /** RegularExpression Id. */
  int STRLIT = 29;
  /** RegularExpression Id. */
  int ADD = 30;
  /** RegularExpression Id. */
  int SUB = 31;
  /** RegularExpression Id. */
  int MUL = 32;
  /** RegularExpression Id. */
  int DIV = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int EQ = 37;
  /** RegularExpression Id. */
  int NE = 38;
  /** RegularExpression Id. */
  int LT = 39;
  /** RegularExpression Id. */
  int LE = 40;
  /** RegularExpression Id. */
  int GT = 41;
  /** RegularExpression Id. */
  int GE = 42;
  /** RegularExpression Id. */
  int ASSGN = 43;
  /** RegularExpression Id. */
  int SEMI = 44;
  /** RegularExpression Id. */
  int COMMA = 45;
  /** RegularExpression Id. */
  int DOT = 46;
  /** RegularExpression Id. */
  int LPAREN = 47;
  /** RegularExpression Id. */
  int RPAREN = 48;
  /** RegularExpression Id. */
  int LBRAC = 49;
  /** RegularExpression Id. */
  int RBRAC = 50;
  /** RegularExpression Id. */
  int LCURLY = 51;
  /** RegularExpression Id. */
  int RCURLY = 52;
  /** RegularExpression Id. */
  int INTLIT = 53;
  /** RegularExpression Id. */
  int DBLLIT = 54;
  /** RegularExpression Id. */
  int ERROR = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"class\"",
    "\"extends\"",
    "\"static\"",
    "\"public\"",
    "\"main\"",
    "\"void\"",
    "\"boolean\"",
    "\"int\"",
    "\"double\"",
    "\"String\"",
    "\"true\"",
    "\"false\"",
    "\"new\"",
    "\"this\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"System\"",
    "\"out\"",
    "\"println\"",
    "<ID>",
    "<STRLIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<INTLIT>",
    "<DBLLIT>",
    "<ERROR>",
    "<token of kind 56>",
  };

}
